# Generated by Django 4.1.13 on 2024-11-13 18:38

import books.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('genres', djongo.models.fields.JSONField(default=list)),
                ('reviews', djongo.models.fields.ArrayField(default=list, model_container=books.models.Review)),
                ('metadata', djongo.models.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
